
"http://justinlilly.com/vim/vim_and_python.html

syntax on
set list listchars=tab:▷⋅,trail:⋅,nbsp:⋅
set statusline=%F%m%r%h%w\ [TYPE=%Y\ %{&ff}]\
\ [%l/%L\ (%p%%)
filetype plugin indent on
au FileType py set autoindent
au FileType py set smartindent
au FileType py set textwidth=79 " PEP-8 Friendly

" be vim not vi
set nocompatible

" Text after a double-quote is a comment
set ruler
set tabstop=4
set shiftwidth=4
set expandtab

" Search Case Insensitive
set incsearch ignorecase hlsearch

" Map Ctrl-A -> Start of line, Ctrl-E -> End of line
map <C-a> <Home>
map <C-e> <End>

" allow keys behave sanely
set whichwrap+=<,>,h,l,[,]

set backspace=eol,start,indent

nmap <c-x> :q!<CR>
nmap <c-o> :w!<CR>
imap <c-x> <Esc>:q!<CR>
cmap <c-o> <Esc>:w!<CR>
