if [ -f ~/.bashrc ]; then
  . ~/.bashrc
fi

########BASH AUTOCOMPLETION SETUP###############
#
if [ -f ~/bin/git-completion.bash ]; then
    . ~/bin/git-completion.bash
fi
#Deal w/ autocompletion and aliases together
complete -o default -o nospace -F _git_branch gb
complete -o default -o nospace -F _git_checkout gc
#
##################################################
